[package]
name = "rust_shyper_os"
version = "0.1.0"
edition = "2021"
authors = ["hukeyang <hky1999@buaa.edu.cn>"]

[lib]
crate-type = ["lib"]  # "lib" required for integration tests
name = "rust_shyper_os"
path = "src/main.rs"

[dependencies]
cfg-if = "1.0.0"
log = "0.4.14"
static_assertions = "1.1.0"

buddy_system_allocator = "0.8.0"
spin = "0.9.2"

cortex-a = { git = "https://github.com/tonnylyz/cortex-a" }

no-std-net = "0.6.0"
ioslice = "0.5.1"
async-task = { version = "4.2", optional = true}
concurrent-queue = { version = "1.2", optional = true }
futures-lite = { version = "1.11", optional = true }

[dependencies.lazy_static]
version = "1.4"
optional = true
features = ["spin_no_std"]

[dependencies.tock-registers]
version = "0.7.0"
default-features = false
features = ["register_types"]

[dependencies.gimli]
version = "0.19.0"
default-features = false
features = ["read", "alloc"]

[dependencies.smoltcp]
version = "0.7"
optional = true
default-features = false
features = [
    "async",
    "ethernet",
    "proto-ipv4",
    "proto-ipv6",
    "socket-tcp",
    # "socket-udp",
    # "std",
    # Enable for increased output
    # "log",
    # "verbose",
]

[features]
default = ["tcp"]

dhcpv4 = ["smoltcp/proto-dhcpv4"]
tcp = [
    "async-task",
    "concurrent-queue",
    "futures-lite",
    "lazy_static",
    "smoltcp",
]

[profile.release]
debug = true