[package]
authors = ["hukeyang <hky1999@buaa.edu.cn>"]
edition = "2021"
name = "rust_shyper_os"
version = "0.1.0"

[lib]
crate-type = ["lib"]
name = "rust_shyper_os"
path = "src/main.rs"

[dependencies]
buddy_system_allocator = "0.8.0"
cfg-if = "1.0.0"
cortex-a = {git = "https://github.com/tonnylyz/cortex-a"}
gimli = {version = "0.19.0", default-features = false, features = ["read", "alloc"]}
log = {version = "0.4.14", features = ["max_level_debug", "release_max_level_debug"]}
# log = {version = "0.4.14", features = ["max_level_info", "release_max_level_info"]}
spin = "0.9.2"
static_assertions = "1.1.0"
tock-registers = {version = "0.7.0", default-features = false, features = ["register_types"]}

## Optional dependencies.
async-task = {version = "4.2", optional = true, default-features = false}
crossbeam-queue = {version = "0.3.5", optional = true, default-features = false, features = ["alloc"]}
crossbeam-utils = {version = "0.8.11", optional = true, default-features = false, features = ["nightly"]}
futures-lite = {version = "1.11", optional = true, default-features = false, features = ["alloc"]}
ioslice = {version = "0.6.0-alpha.2", optional = true, default-features = false}
lazy_static = {version = "1.4", optional = true, features = ["spin_no_std"]}
no-std-net = {version = "0.6.0", optional = true}
lru = {version = "0.7.8", optional = true}

[dependencies.smoltcp]
default-features = false
features = [
  "alloc",
  "async",
  "ethernet",
  "proto-ipv4",
  "proto-ipv6",
  "socket-tcp", # "socket-udp",  # "std",
  # Enable for increased output
  # "log",
  # "verbose",
]
optional = true
version = "0.7"

[dependencies.fatfs]
default-features = false
features = ["lfn", "alloc", "unicode", "log_level_trace"]
git = "https://github.com/rafalh/rust-fatfs"
optional = true
version = "0.4"

[features]
default = ["alloc", "qemu", "tcp", "oldfs", "fs", "smp"]
# default = ["alloc","tcp","shyper"]
alloc = []
dhcpv4 = ["smoltcp/proto-dhcpv4"]
fs = [
  "fatfs",
  "lru",
  "ioslice",
]
oldfs = [
  "fatfs",
  "lru",
]
qemu = []
shyper = []
tcp = [
  "async-task",
  "futures-lite",
  "lazy_static",
  "smoltcp",
  "crossbeam-queue",
  "ioslice",
  "no-std-net",
]
smp = [
  "crossbeam-utils"
]

[profile.release]
debug = true
