[package]
authors = ["hukeyang <hky1999@buaa.edu.cn>"]
edition = "2021"
name = "net_demo"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
no-std-net = "0.6.0"

[dependencies.rust_shyper_os]
default-features = false
path = "../../"

[features]
default = ["qemu"]
qemu = [
    "alloc",
    "rust_shyper_os/alloc",
    "rust_shyper_os/tcp", 
    "rust_shyper_os/qemu"
    ]
shyper = [
    "alloc", 
    "rust_shyper_os/alloc", 
    "rust_shyper_os/tcp", 
    "rust_shyper_os/shyper"
    ]
alloc = []

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"
