[package]
name = "net_demo"
version = "0.1.0"
edition = "2021"
authors = ["hukeyang <hky1999@buaa.edu.cn>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
no-std-net = "0.6.0"

[dependencies.rust_shyper_os]
path = "../../"
default-features = false
features = [
    "alloc",
    # "qemu",
    "shyper",
    "tcp",
]

[features]
default = ["alloc"]
alloc = []

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"
